const { cmd } = require('../command');

// Voice links (MP3s)
const voiceLinks = [
    'https://files.catbox.moe/4i7ccz.mp3',
    'https://files.catbox.moe/c0rswx.mp3',
    'https://files.catbox.moe/hgyeth.mp3',
    'https://files.catbox.moe/lleedr.mp3',
    'https://files.catbox.moe/5q1il0.mp3',
    'https://files.catbox.moe/is3w5r.mp3',
    'https://files.catbox.moe/rmb9hb.mp3',
    'https://files.catbox.moe/94f3ah.mp3',
    'https://files.catbox.moe/r59jbk.mp3',
    'https://files.catbox.moe/vazu0l.mp3',
    'https://files.catbox.moe/ed46vg.mp3',
    'https://files.catbox.moe/3arfe3.mp3',
    'https://files.catbox.moe/6pzpfr.mp3',
    'https://files.catbox.moe/dh3724.mp3',
    'https://files.catbox.moe/u6yge7.mp3',
    'https://files.catbox.moe/ciierd.mp3',
    'https://files.catbox.moe/b05qvd.mp3',
    'https://files.catbox.moe/w4w5y4.mp3',
    'https://files.catbox.moe/21wlvr.mp3',
    'https://files.catbox.moe/lun14u.mp3',
    'https://files.catbox.moe/7g9vsa.mp3',
    'https://files.catbox.moe/jga5ad.mp3',
    'https://files.catbox.moe/pa4760.mp3',
    'https://files.catbox.moe/5w8vn2.mp3',
    'https://files.catbox.moe/n2qj1a.mp3',
    'https://files.catbox.moe/o38jkp.mp3',
    'https://files.catbox.moe/i88eyq.mp3',
    'https://files.catbox.moe/et8fcl.mp3',
    'https://files.catbox.moe/c7lks6.mp3',
    'https://files.catbox.moe/mjq16o.mp3',
    'https://files.catbox.moe/97q2ig.mp3',
    'https://files.catbox.moe/6l9ush.mp3',
    'https://files.catbox.moe/qvxtep.mp3',
    'https://files.catbox.moe/kmoy0h.mp3'
];

// Text messages list
const textMessages = [
    "👋 හෙලෝ! කොහොමද ඉන්නෙ?",
    "🤖 මම ඔයාට උදව් කරන්න කැමතියි!",
    "🎵 මෙන්න bot එකේ random voice එකක්:",
    "🛸 අපි ගමන් කරනවා...",
    "💡 Bot එක always active!",
    "🌟 හොඳ දවසක් වේවා!",
    "🚀 හැමදාම ලස්සයි ඔයා ❤️‍🩹!",
    "ඔයා සතුටින් නේද 😅 විශේෂ දෙයක් ගැන කතාකරන්න ඕනිද..? 🤔",
  "හායි යාලුවා කොහොමද ඉතින් ඔයාට ☺️",
  "හපොයි කණගාටුවක් දැනෙනවා ඔබ දුකින්ද ඉන්නේ 🥺",
  "සිතගන්න යාලුවා ඔයා ගොඩක් හොද කෙනෙක් ☺️🫡",
  "හපොයි 🤭🤭🤭 සතුටින් වගේ අද නම්",
  "ඉතින් යාළුවා ඔයා ප්‍රශ්නයකද ඉන්නේ..? 🤔",
  "සතුටක් හොයන්න හරි අමාරුයි 🥺❤️‍🩹",
  "ආයෙත් හිතන්න එපා, ඔයාට ලැබෙයි ආදරේ ❤️",
  "කොහොමද අද දවස ? 🫶",
  "හිතන්නත් අමාරුයි, හැමෝම busy 🤯",
  "දවස සුභ අරඹන්න 🕊️",
  "අදත් කාර්යබහුලද ? 🏃‍♂️",
  "මතක තබාගන්න, ඔයා විශේෂ කෙනෙක් ❤️",
  "ඇය ගැන හිතනවාද තවම? 🥺",
  "මට කිවුවා ඔයා කැමති කෙනෙක් කියලා 🤭",
  "ඔයාට හොඳ හීන බලාපොරොත්තු වෙනවා 🌙",
  "සතුටේ අරුත තවත් සොයමු ❤️‍🔥",
  "මට කියන්න, කවදා හොඳ වෙයි කියලා 🕊️",
  "අදත් coffee එක අමතක වෙන්න එපා ☕",
  "ඔයාට පුළුවන් කියලා විශ්වාස කරනවා ✊",
  "කාලය හැමදේම සුව කරනවා 🍃",
  "ආයෙත් ආදරේ කරමුද? 🤍",
  "මම ඉන්නවා ඔයාට ✨",
  "බලාපොරොත්තු තියන්න ☀️",
  "අදත් ලඟට එන්න ඕනේ ❤️",
  "ඔයාට හැමදාම support කරනවා 🫶",
  "නොදන්නා අයත් යාලු වෙන්න පුළුවන් 🤝",
  "එල මචං! 😎",
  "මොනවද අද කරන්නේ ? 😁",
  "නිකන්ම chat එකක් දාමු 🔥",
  "හායි මිතුරා 👋",
  "ඔයාගේ සිහින මට කියන්න 🌠",
  "හිතන්න හොඳ දේවල් ගැන ❤️‍🩹",
  "බය වෙන්න එපා, ඔයාට හැකියි 💪",
  "මොකක්ද අද හැමෝම කරන්නේ ? 🤗",
  "මම සතුටින් ඉන්නෙ ඔයා හොඳින් තියෙන්නේ කියලා 😍",
  "හිතෙනවද ආයෙත් පාවිච්චි කරන්න 🤭",
  "අදත් හැමදේ හොඳින් යන්න කියලා ප්‍රාර්ථනා 🙏",
  "ඔයා වගේ මිතුරන් අහිමි වෙන්න එපා 🫶",
  "හිතාගන්න අමාරුද sometimes? 😔",
  "අපි හැමදාම connected 🛸",
  "ඇවිත් chat එකක් දාන්න 😉",
  "ඔයාට ජය වේවා ❤️",
  "මට විශ්වාසයි ඔයාට පුළුවන් 🌟",
  "අදත් හොඳ vibes 🎶",
  "ඔයාට special දෙයක් තියෙනවද කියන්න 🤔",
  "කාලේ ගියත් මතක තියාගන්න 🤍",
  "ඔයාට ලැබෙයි ජයග්‍රහණයක් 🏆",
  "සුභ රාත්‍රියක් 🌙",
  "දැනටමත් අලුත් දෙයක් plan කරනවද ? 📝",
  "මට ඔයාගෙන් ගොඩක් ඉගෙන ගන්න පුළුවන් 📚",
  "එන්න අපි කතා කරමු 🫡",
  "හොඳද මිතුරා 🫶",
  "මතක තියාගන්න, ආදරේ අමතක කරන්න එපා ❤️",
  "හැමදාම ලග ඉන්නවා කියලා වාඩි වෙන්න 🫂",
  "ආයෙත් ඇවිල්ල කතා කරන්න 😉",
  "මට ඔයාගෙ අදහස ඕනි 🤔",
  "සුභ දවස් වේවා 🌞",
  "සිත මෘදු කරලා බලන්න 🕊️",
  "දැනෙන්නෙ අමුතුද අද? 😯",
  "ඔයාට ලැබෙනවා හොඳ news 📣",
  "අදත් දෙයක් හැමදා වගේම 🔥",
  "ඔයා හොඳ මිතුරෙක් ❤️",
  "ඇවිල්ල රැඳෙන්න 🫂",
  "මතකද අපි කලින් කතා කලේ 🫶",
  "ඔයාට කැමති song එක කියන්න 🎵",
  "මට ඔයාගේ පෝස්ට් දැක්කා 🤭",
  "හිතාගෙන ඉන්න එක sometimes painful 🥺",
  "දවස ගෙවන එක easy වෙන්න කියලා ප්‍රාර්ථනා 🙏",
  "මට ඔයාට proud වෙන්න පුළුවන් ✊",
  "කවදා හෝ හමුවෙමු ❤️",
  "මට හොඳ කතා තියෙනවා කියන්න 🤫",
  "කතා කරන එක සතුටක් 😊",
  "ඔයාට මොනවද ඕනි කියන්න 🤔",
  "අදත් කැමතිද chat කරන්න ? 😁",
  "අදාල කෙනෙකුගෙන් අවසර අරගෙන යමු 🤝",
  "තව පටන් ගන්න එක අමාරුද sometimes ? 😔",
  "ඔයාට හොඳ memory තියෙනවද 📸",
  "හොඳම මිතුරා 👬",
  "මම ready ❤️‍🔥",
  "ඔයා ගැන හිතනවා ❤️",
  "දැන්මම ආයෙත් call එකක් දාමුද ? 📞",
  "එන්න, දන්න දෙයක් share කරන්න 🤗",
  "සුබම සුබ 🌟",
  "එන්න ඔයාගේ අලුත් project ගැන කියන්න 🛠️",
  "මට අවශ්‍යයි ඔයාගේ help 🙏",
  "එල මිතුරා 😎",
  "හිතන හැමදේම සාර්ථක වේවා ✨",
  "ඔයාට පුළුවන් කියලා විශ්වාසයි ❤️",
  "හොඳ යාලුවෙක් වගේ ඔයා 🫶",
  "අදත් හැමදා වගේම active ද? 💬",
  "මට කියන්න ඔයාට විශේෂ plan එකක් තියෙනවද 📝",
  "හිතන හැමදේම reality කරන්න ඕනේ 💪",
  "මට හොඳ විශ්වාසයක් තියෙනවා ඔයාට ☀️",
  "ඔයාගෙ ජීවිතේ ගමන් smooth වේවා 🛤️",
  "දැනෙන්නෙ lonely ද sometimes ? 😔",
  "මට හිතෙනවා ඔයා deserves happiness ❤️",
  "හිතාගෙන ඉන්න එක sometimes hard 😕",
  "සුභම සෙනසුරාදාක් 🫡",
  "ආයෙත් අරමු chat එක 😉",
  "ඔයාට කවදාහරි යාලුවා අහිමි වෙලාද 🥺",
  "දවසට සුභාරංචි වේවා 🌟",
  "මට ආදරෙයි ඔයාට ❤️",
  "එන්න bot එකට msg එකක් දාන්න 📲",
  "ඔයාගේ කතා මට අහන්න හොඳයි 👂",
  "දැන්ම reply කරන්න 😉",
  "ඔයා හොඳම එක ❤️",
  "සිත මෘදු කරලා හොඳ විදියට සලකා බලන්න 🕊️",
  "මට ඔයාව මතක් වෙනවා 🙃",
  "ඔයාට තියෙන skills ලොකු දෙයක් ✨",
  "අදත් වැඩ්ඩ ද ? 👨‍💻",
  "කාලය අතුරුදහන් වෙනවා sometimes ⏳",
  "ඔයාට විශේෂ news එකක් ලැබෙයි 📣",
  "හිතන්නත් එපා අතහැර යන්න 🥺",
  "ඔයා deserve කරනවා හොඳම දෙවල් ❤️",
  "ඔයාට wish කරනවා best ජීවිතයක් 🌈",
  "හිතෙනවද අද happy වෙන්න ? 😁",
  "කවදාහරි යාලුවෝ අහිමි වෙනවා 🫂",
  "ඔයාට support කරනවාම guaranteed 🫡",
  "මට ඔයාගෙන් inspire වෙනවා 🤝",
  "දැන්මම මට කියන්න 🗣️",
  "ඔයාටමයි ❤️",
  "හිතෙනවා sometimes alone 😔",
  "ඔයාට ආදරෙයි කියන්න අමතක වෙන්න එපා ❤️",
  "සුබ රාත්‍රියක් wish කරනවා 🌙",
  "මිතුරන් අහිමි වෙන එක painful 🥺",
  "කාලේ කියලා අමතක වෙන්න එපා 🕰️",
  "ඔයා deserve කරනවා peace 🕊️",
  "අද chat එක අමාරුද ? 🤔",
  "ඔයාට support always මම ඉන්නවා 🫶",
  "හොඳම යාලුවෙක් 🫂",
  "හිතන්න එපා alone කියලා ❤️",
  "කතා කරන එක happiness එකක් ❤️",
  "ඔයා deserve කරනවා better life ✨",
  "දැන්ම යන්න එපා 🤭",
  "ඔයාට විශ්වාසයි ඔයා හොඳම කෙනෙක් කියලා ❤️",
  "අදත් සතුටක් spread කරමු 🕊️",
  "හොඳම හිතය තියෙනවා ඔයාට ❤️",
  "ඔයා deserve කරනවා win 🏆",
  "මට ඔයාගෙ progress බලලා proud වෙනවා ❤️",
  "හිතාගෙන ඉන්න හොඳම දෙවල් ගැන 🫡",
  "ඔයාට අළුත් අරමුණු ලැබේවා 🌠",
  "සුභම සෙනසුරාදාක් 🫡",
  "ඔයාට අලුත්ම chance එකක් ලැබේවා ✨",
  "හිතෙනවද sometimes sad 😔",
  "ඔයා deserve කරනවා happiness ❤️",
  "දැනෙන්නෙ අමුතුද sometimes ? 🤔",
  "ඔයාට ලැබෙයි ආදරේ ❤️",
  "ඔයා deserve කරනවා success 🏆",
  "හිතාගෙන ඉන්න ඔයාම තමයි හොඳම කෙනා ❤️",
  "ඔයා deserve කරනවා respect 🤝",
  "හිතන හැමදේම අවසන් කරන්න පුළුවන් 💪",
  "ඔයා deserve කරනවා විශාල අනාගතයක් 🌈"
];

cmd({
    pattern: "test.js",
    react: "🛸",
    alias: ["✓", "list", "music"],
    desc: "Send document audio with caption",
    category: "main",
    use: '.menu3',
    filename: __filename
},
async (conn, mek, m, { from, pushname, reply }) => {
    try {
        // pick a random voice
        const randomVoiceLink = voiceLinks[Math.floor(Math.random() * voiceLinks.length)];

        // pick a random text message
        const randomText = textMessages[Math.floor(Math.random() * textMessages.length)];

        // send as document (with caption)
        await conn.sendMessage(from, {
            document: { url: randomVoiceLink },
            fileName: "voice.mp3",
            mimetype: "audio/mp3",
            caption: `👨🏻‍💻 *${pushname}*\n\n${randomText}`
        });

    } catch (e) {
        console.log(e);
        reply(`Error: ${e.message}`);
    }
});
